version: '3'
name: tspark
services:
  api:
    container_name: tspark-api
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    ports:
      - '3333:3333'
    environment:
      - APP_NAME=TSpark
      - JWT_SECRET=this is a very secret secret
      - PORT=3333
      - SALT_ROUNDS=12
  client:
    container_name: tspark-client
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    ports:
      - '4200:4200'
    environment:
      - TSPARK_APP_APP_NAME=TSpark
      - TSPARK_APP_API_URL=http://localhost:3333/api
