version: '3'
name: tspark
services:
  api:
    container_name: tspark-api
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    command: ['node', '--inspect=0.0.0.0:9229', 'packages/api/dist/src/index.js']
    ports:
      - '3333:3333'
      - '9229:9229'
    environment:
      - APP_NAME=TSpark
      - JWT_SECRET=this is a very secret secret
      - PORT=3333
      - SALT_ROUNDS=12
  client:
    container_name: tspark-client
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    ports:
      - '8080:80'
    environment:
      - TSPARK_APP_APP_NAME=TSpark
      - TSPARK_APP_API_URL=http://localhost:3333/api
